export const BusinessPageQuery= `query businessPlanningPageEntryQuery {
    businessPlanningPage(id: "7CSmDHix9dirFWBqznPuiK") {
     topHeader{
      title
      subTitle
      description
      image{
        url
        title
      }
    }
    bannerInfo{
      json
    }
      businessDataCollection{
        items{
          title
          listItems
          image{
            url
            title
          }
          imageDirection
        }
      }
      diversityLaborMarketData{
        title
        description
        talentDataRefCollection{
          items{
            title
            description
            logo{
              url
              title
            }
          }
        }
      }
      exploreOur{
        title
        description
      }
      blogsCollection{
        items{
          title
          subTitle
          listItems
          image{
            url
            title
          }
          imageDirection
        }
      }
      getStartedBanner{
        title
        description
        buttonTitle
        buttonUrl
      }
    }
  }`