export const CaseStudiesQuery = `query caseStudyPagesEntryQuery {
  caseStudyPages(id: "2DLmTLCGohKpuiytt4BnFH") {
    title
    description
    casesCollection{
      items{
        customer{
          title
          description
          showOnCustomerPage
          logo{
            url
            title
          }
          buttonName
          buttonUrl
        }
        caseStudyName
        sys{
          id
        }
        slug
      }
    }
    topEnterprisePersonDetailsCollection{
      items{
        name
        designation
        description
        personImage{
          url
          title
        }
        url
        urlName   
      }
    }
    getStartedBanner{
      title
      description
      buttonTitle
      buttonUrl
    }
    metaTags{
      title
      metaTagsCollection{
        items{
          name
          content
          mataTagFor
        }
      }
    }
    schemaQuestionAnswerCollection{
      items{
        question
        answer
      }
    }
  }
}`