export const CustomerPageQuery = `query customersEntryQuery {
    customers(id: "4ornVv32ksqOine6B35CGi") {
     title
      description
      customerCollection{
        items{
          title
          description
          logo{
            url
            title
          }
          buttonName
          buttonUrl
        }
      }
      topEnterprisePersonDetailsCollection{
        items{
          name
          designation
          description
          personImage{
            url
            title
          }
          url
          urlName
        }
      }
      banner{
        title
        description
        buttonTitle
        buttonUrl
      }
    }
  }`