export const HomePageQuery = `query homePageEntryQuery {
    homePage(id: "1NkWy2baKtD6vtNZxAqJ50") {
     title
      slug
      topHeader{
        title
        description
        image{
          title
          url
        }
      }
      partnersLogoCollection{
        items{
          title
          url
        }
      }
      videoId
      blogsCollection{
        items{
          title
          subTitle
          listItems
          image{
            title
            url
          }
          imageDirection
        }
      }
      statisticsTitle
      statisticsItemsCollection{
        items{
          title
          statisticsData
          description
        }
      }
      topEnterprisesTitle
      topEnterprisesClientsCollection{
        items{
          name
          designation
          description
          personImage{
            title
            url
          }
          url
          urlName
        }
      }
      exploreHorseflyBanner{
        title
        buttonName
        buttonUrl
      }
      metaTag{
        title
        metaTagsCollection{
          items{
            name
            content
            mataTagFor
          }
        }
      }
      schemaQuestionAnswerCollection{
        items{
          question
          answer
        }
      }
    }
  }`