export const LaborMarketAnalyticsQuery= `query laborMarketAnalyticsPageEntryQuery {
    laborMarketAnalyticsPage(id: "1jA1yQTJiYZUUfKwoZSSug") {
    topHeader{
      title
      description
      image{
        url
        title
      }
    }
      banner{
        title
        description
      }
      notes{
        note
        descriptionOverview
      }
      laborMarketAnalyticsProvide{
        title
        description
        talentDataRefCollection{
          items{
            title
            description
            logo{
              url
              title
            }
          }
        }
      }
      laborMarketAnalyticsAndTools{
        title
        description
        laborMarketAnalyticsAndItemsCollection{
          items{
            title
            image{
              url
              title
            }
          }
        }
      }
      usesOfLaborMarketData{
        title
        laborMarketDataCollection{
          items{
            title
            description
            image{
              title
              url
            }
          }
        }
      }
      findLaborMarketData{
        title
        description
      }
      contactHorsefly{
        title
        buttonName
        buttonUrl
      }
      metaTags{
        title
        metaTagsCollection{
          items{
            name
            content
            mataTagFor
          }
        }
      }
        schemaQuestionAnswerCollection{
          items{
            question
            answer
          }
        }
        faqsTitle
        faqsCollection{
          items{
            question
            faqAnswer{
              json
            }
          }
        }
    }
  }`