export const RPOPageQuery = `query rpoRecruitmentPageEntryQuery {
    rpoRecruitmentPage(id: "5P4aN8FciJXVLough3o0g8") {
      sys {
        id
      }
      title
      topHeader{
        title
        description
        image{
          url
          title
        }
      }
      rpoClientTitle
      rpoClientsCollection{
        items{
          name
          designation
          description
          urlName
          url
        }
      }
      bannerInfo{
        json
      }
      theExpertVoice{
        title
        description
        steamlineItemsCollection{
          items{
            title
            description
          }
        }
      }
      toolForRpOsRecruitmentTeams{
        title
        description
        talentDataRefCollection{
          items{
            title
            description
            logo{
              url
              title
            }
          }
        }
      }
      infoBanner{
        title
        description
      }
      blogsCollection{
        items{
          title
          subTitle
          listItems
          image{
            url
            title
          }
          imageDirection
        }
      }
      getStartedBanner{
        title
        description
      }
      metaTags{
        title
        metaTagsCollection{
          items{
            name
            content
            mataTagFor
          }
        }
      }
        schemaQuestionAnswerCollection{
          items{
            question
            answer
          }
        }
    }
  }`