export const TalentAnalyticsQuery = `query talentAnalyticsPageEntryQuery {
    talentAnalyticsPage(id: "6xCpC15VVF1vocnPWkv9TW") {
     title
      topHeader{
        title
        description
        image{
          url
          title
        }
      }
      blogsCollection{
        items{
          title
          listItems
          image{
            url
            title
          }
          imageDirection
        }
      }
      talentAnalyticsTools{
        title
        description
        talentDataRefCollection{
          items{
            title
            description
            logo{
              url
              title
            }
          }
        }
      }
      banner{
        title
        description
      }
      whoCanBenefit{
        title
        description
        laborMarketAnalyticsAndItemsCollection{
          items{
            title
            image{
              url
              title
            }
          }
        }
      }
      benefitsOfHorsefly{
        title
        benefitsDataCollection{
          items{
            title
            description
          }
        }
      }
      strategicBusinessUses{
        title
        laborMarketDataCollection{
          items{
            title
            description
            image{
              url
              title
            }
          }
        }
      }
      horseflyAnalyticsPlatformBanner{
        title
        description
      }
      faqTitle
      contactHorseflyBanner{
        title
        buttonName
        buttonUrl
      }
      metaTags{
        title
        metaTagsCollection{
          items{
            name
            content
            mataTagFor
          }
        }
      }
      schemaQuestionAnswerCollection{
        items{
          question
          answer
        }
      }
      faqsCollection{
        items{
          question
          faqAnswer{
            json
          }
        }
      }
    }
  }`