export const TalentAquisitionQuery = `query talentAcquisitionPlatformEntryQuery {
    talentAcquisitionPlatform(id: "3g3CK02BaMvbg3u20dQjfX") {
          title
      topBanner{
        title
        description
        image{
          url
          title
        }
      }
      banner{
        json
      }
      streamlineYourTalent{
        title
        description
        steamlineItemsCollection{
          items{
            title
            description
          }
        }
      }
      toolsForRecruitment{
        title
        description
        talentDataRefCollection{
          items{
            title
            description
            logo{
              url
              title
            }
          }
        }
      }
      alentAcquisitionAnalytics{
        title
        description
      }
      blogsCollection{
        items{
          title
          subTitle
          listItems
          image{
            url
            title
          }
          imageDirection
        }
      }
      getStartedBanner{
        title
        description
      }
      metaTags{
        title
        metaTagsCollection{
          items{
            name
            content
            mataTagFor
          }
        }
      }
        faqSchemaQuestionsanswerCollection{
          items{
            question
            answer
          }
        }
    }
  }`