export const TalentMarketDataQuery = `query talentMarketDataPageEntryQuery {
    talentMarketDataPage(id: "1J2EnpQ9y8LOXDSxsV6nDT") {
        title
      topHeader{
        title
        description
        image{
          url
          title
        }
      }
      banner{
        title
        description
      }
      problemSectionTitle
      problemSectionDescription
      problemAndSolutionsCollection{
        items{
          questionType
          question
          answer
        }
      }
      premierTalentAnalyticsPlatform{
        title
        description
        talentDataRefCollection{
          items{
            title
            description
            logo{
              url 
              title
            }
          }
        }
      }
      exploreBanner{
        title
        description
      }
      blogCollection{
        items{
          title
          subTitle
          listItems
          image{
            url
            title
          }
          imageDirection
        }
      }
      getStartedBanner{
        title
        description
        buttonTitle
        buttonUrl
      }
      metaTags{
        title
        metaTagsCollection{
          items{
            name
            content
            mataTagFor
          }
        }
      }
        schemaQuestionAnswerCollection{
          items{
            question
            answer
          }
        }
    }
  }`