export const TalentAquisitionQuery = `query talentAcquisitionPlatformEntryQuery {
  talentAcquisitionPlatform(id: "wrFM7Qa7G9iKq6XVwkKhf") {
        title
    topBanner{
      title
      description
      image{
        url
        title
      }
    }
    banner{
      json
    }
    streamlineYourTalent{
      title
      description
      steamlineItemsCollection{
        items{
          title
          description
        }
      }
    }
    toolsForRecruitment{
      title
      description
      talentDataRefCollection{
        items{
          title
          description
          logo{
            url
            title
          }
        }
      }
    }
    alentAcquisitionAnalytics{
      title
      description
    }
    blogsCollection{
      items{
        title
        subTitle
        listItems
        image{
          url
          title
        }
        imageDirection
      }
    }
    getStartedBanner{
      title
      description
    }
  }
}`