export const WhyHorseflyQuert = `query whyHorseflyEntryQuery {
    whyHorsefly(id: "3mfvcfFwFckIf0WHWkSHMV") {
     title
      slug
      topBanner{
        title
        description
        image{
          url
          title
        }
      }
      bannerData{
        title
        description
      }
      talentDataRef{
        title
        description
        talentDataRefCollection{
          items{
            title
            description
            logo{
              title
              url
            }
          }
        }
      }
      questionanswerTitle
      questionanswerDescription
      questionanswerListsCollection{
        items{
          questionType
          question
          answer
        }
      }
      exploreOurData{
        title
        description
        slug
      }
      blogsCollection{
        items{
          title
          subTitle
          listItems
          image{
            title
            url
          }
          imageDirection
          slug
        }
      }
      getStartedBanner{
        title
        description
        buttonTitle
        buttonUrl
        slug
      }
      metaTags{
        title
        metaTagsCollection{
          items{
            name
            content
            mataTagFor
          }
        }
      }
      faqSchemaQuestionsanswerCollection{
        items{
          answer
          question
        }
      }
    }
  }`